### ISSUE TITLE
Deployment using now gives error

### ISSUE THREAD

**Issue by moritzmorgenroth** [graphql-boilerplates/typescript-graphql-server#88] opened 2018-01-17 21:31 UTC
Hi, 

I tried deploying the typescript-advanced boilerplate using the same process that is described in the  
[tutorial](https://www.prismagraphql.com/docs/tutorials/graphql-server-development/deployment-with-now-ahs1jahkee) in the prisma docs. For the node boilerplate it worked like a charm. 

However, using the typescript version I get this error: 

`
> node_modules/@types/zen-observable/index.d.ts(31,14): error TS2300: Duplicate identifier 'Subscriber'.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! xxxxxxx @ build: `rimraf dist && tsc`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the xxxxxxx@ build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2018-01-17T21_13_11_731Z-debug.log
> Error! The build step of your project failed. To retry, run `now --force`.
`

I tried deploying to Heroku and got a similar error. Im rather new to node, any ideas would be appreciated! 

Thx in advance!

**Comment by marktani** [comment] 2018-01-19 20:06
This is an issue in `apollo-link`: https://github.com/apollographql/apollo-link/issues/419

Please read https://www.graph.cool/forum/t/prisma-trying-to-deploy-to-now-and-getting-error/2179?u=nilan for background information on this problem.

**Comment by marktani** [comment] 2018-01-22 10:42
Closing this as there is a workaround (described in the Forum), and the issue is outside of this repo.

**Closed by marktani** 2018-01-22 10:42 UTC
Labels: bug
